from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from typing import Any, Optional

logger = logging.getLogger(__name__)


class BaseSpecialistAgent(ABC):
    """Abstract base class for all document-type specialist agents.

    Each specialist has two entry points:

    1. :meth:`analyze_image` — initial analysis given a debate question.
    2. :meth:`final_analysis` — refined answer after receiving critique.

    Subclasses must implement both methods and a ``SYSTEM_MESSAGE``
    class attribute describing the agent's role.
    """

    SYSTEM_MESSAGE: str = ""

    @abstractmethod
    def analyze_image(
        self,
        image_path: str,
        question: str,
        debate_question: str,
    ) -> str:
        """Produce an initial analysis of the document image.

        Args:
            image_path: Path (or URL) to the document image.
            question: The original user question.
            debate_question: The challenging question generated by
                the debate agent.

        Returns:
            A structured text analysis.
        """

    @abstractmethod
    def final_analysis(
        self,
        image_path: str,
        question: str,
        debate_question: str,
        original_answer: str,
        alternative_answer: str,
        debate_result: str,
        critique: str,
    ) -> str:
        """Produce a refined final answer after debate and critique.

        Args:
            image_path: Path (or URL) to the document image.
            question: The original user question.
            debate_question: The debate agent's challenging question.
            original_answer: Answer A from stage 1.
            alternative_answer: Answer B from stage 1.
            debate_result: The initial analysis output.
            critique: The critic agent's critique.

        Returns:
            The agent's final, confident answer.
        """


class BaseTextAgent(ABC):
    """Abstract base class for text-only agents (debate, language expert, etc.)."""

    @abstractmethod
    def generate(self, prompt: str, **kwargs: Any) -> str:
        """Generate a text response."""
